version: "3.9"

services:
    mongo:
        image: mongo:7.0
        container_name: dev-mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: usuario
            MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
